apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
  name: simple
spec:
  version: "0.0.362"
  nodeEnvironment: production
  coordinators:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - main-1.stackable.demo
        config:
          coordinator: true
          nodeId: "ffffffff-ffff-ffff-ffff-ffffffffffff"
          nodeDataDir: /tmp/trino/data
          metricsPort: 10200
          httpServerHttpPort: 8080
          discoveryUri: http://localhost:8080
  workers:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - worker-1.stackable.demo
                - worker-2.stackable.demo
                - worker-3.stackable.demo
        replicas: 1
        config:
          nodeId: "ffffffff-ffff-ffff-ffff-fffffffffffe"
          nodeDataDir: /tmp/trino/data2
          metricsPort: 10201
          httpServerHttpPort: 8081
          discoveryUri: http://localhost:8080
